### ISSUE TITLE
Tutorial- Change Collected to Revenue collected on dashboard

### ISSUE THREAD

**Issue by ohnishant** [ohnishant/jusadashboard#3]
Dashboard says Collected in the collected card, i think this should be changed to `Revenue Collected`

![image](https://github.com/ohnishant/jusadashboard/assets/52268717/9c18141d-23dd-45e0-9458-e1a9ac007ef1)

**Comment by kgaurav8026** [comment]
Can I contribute 😜

**Comment by justtravneet** [comment]
I can change this Collected to Recent Collected

**Comment by ohnishant** [comment]
> I can change this Collected to Recent Collected

Sounds good, go ahead
